# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 21) do

  create_table "computerskills", :force => true do |t|
    t.column "name",       :string
    t.column "cstype",     :string
    t.column "level",      :string
    t.column "experience", :string
    t.column "klang",      :integer
  end

  create_table "destcurrs", :force => true do |t|
    t.column "inserat",          :text
    t.column "contact_email",    :string
    t.column "contact_web",      :string
    t.column "contact_person",   :string
    t.column "contact_company",  :string
    t.column "contact_note",     :text
    t.column "contact_ams",      :boolean
    t.column "curr_sent_at",     :date
    t.column "colloquio_at",     :date
    t.column "email_motivaz",    :text
    t.column "note",             :text
    t.column "risultato",        :string
    t.column "kcurr_saved",      :integer
    t.column "inserat_filename", :string
  end

  create_table "educations", :force => true do |t|
    t.column "from",         :date
    t.column "to",           :date
    t.column "title",        :string
    t.column "skills",       :text
    t.column "organisation", :string
    t.column "level",        :string
    t.column "klang",        :integer
  end

  create_table "filecurrsaveds", :force => true do |t|
    t.column "curr_title",    :string
    t.column "curr_filename", :string
    t.column "kuser",         :integer
    t.column "content",       :text
  end

  create_table "identities", :force => true do |t|
    t.column "firstname",   :string
    t.column "lastname",    :string
    t.column "address",     :string
    t.column "fax",         :string
    t.column "mobile",      :string
    t.column "email",       :string
    t.column "web",         :string
    t.column "birthdate",   :date
    t.column "gender",      :string
    t.column "nationality", :string
    t.column "klang",       :integer
    t.column "familystate", :string
  end

  create_table "identpictures", :force => true do |t|
    t.column "foto_filename", :string
    t.column "kindetity",     :integer
    t.column "content_type",  :string
    t.column "foto",          :text
  end

  create_table "languages", :force => true do |t|
    t.column "isoname", :string
  end

  create_table "languageskills", :force => true do |t|
    t.column "name",  :string
    t.column "level", :string
    t.column "lang",  :string
    t.column "klang", :integer
  end

  create_table "miscstuffs", :force => true do |t|
    t.column "misc",   :text
    t.column "mstype", :string
    t.column "klang",  :integer
  end

  create_table "otherskills", :force => true do |t|
    t.column "skill",  :text
    t.column "sktype", :string
    t.column "klang",  :integer
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"
  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"

  create_table "users", :force => true do |t|
    t.column "name",            :string
    t.column "hashed_password", :string
    t.column "salt",            :string
  end

  create_table "workexperiences", :force => true do |t|
    t.column "from",       :date
    t.column "to",         :date
    t.column "position",   :string
    t.column "activities", :text
    t.column "employer",   :text
    t.column "sector",     :string
    t.column "tag",        :string
    t.column "klang",      :integer
  end

end
